blank_issues_enabled: false
contact_links:
  - name: General discussion
    url: https://github.com/edumacator/pbl-project-manager/discussions
    about: Use discussions or other agreed channels for non-actionable conversation.
